# Generated by Django 3.1.5 on 2021-01-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20210123_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendamodel',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
