# Generated by Django 3.1.5 on 2021-02-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patrimonio_br', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patrimonio_usa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro_br', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro_usa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('abertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vol_implicidta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nacional', models.BooleanField()),
            ],
        ),
    ]
