# Generated by Django 3.1.5 on 2021-02-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_variacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcaoModel',
            new_name='RelatorioCompletoModel',
        ),
    ]
